# Use an official Python runtime as a parent image
FROM python

# Set the working directory in the container
WORKDIR /app

# Create a simple Python script
RUN echo 'print("Hello World")' > hello.py

# Run the Python script
CMD ["python", "hello.py"]
